name: Message Board CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  backend:
    uses: ./.github/workflows/gradle.yml

  frontend:
    uses: ./.github/workflows/gatsby.yml

  compose:

    runs-on: ubuntu-latest
    needs: [ backend, frontend ]

    steps:
      - uses: actions/checkout@v6.0.1
      - name: Compose Docker services
        run: docker compose build